function[x_rot,y_rot,z_rot] = invers_rot (x, y, z, theta, phi, eta)
% syms phi theta eta x y z;
% A = ...
% [ cos(eta)   0   sin(eta);...
%  0        1        0     ;...
% -sin(eta)   0    cos(eta)]*...
% [  cos(theta)   -sin(theta)   0;...
% sin(theta)   cos(theta)   0;...
% 0          0        1]*...
% [ 1    0        0 ;...
% 0 cos(phi) -sin(phi);...
% 0 sin(phi) cos(phi)]*[x ;z ;y ] 
                           
x_rot = y*(cos(phi)*sin(eta) + cos(eta)*sin(phi)*sin(theta)) + z*(sin(eta)*sin(phi) - cos(eta)*cos(phi)*sin(theta)) + x*cos(eta)*cos(theta);
y_rot = y*(cos(eta)*cos(phi) - sin(eta)*sin(phi)*sin(theta)) + z*(cos(eta)*sin(phi) + cos(phi)*sin(eta)*sin(theta)) - x*cos(theta)*sin(eta);
z_rot = x*sin(theta) + z*cos(phi)*cos(theta) - y*cos(theta)*sin(phi);

end