function [x_rot,y_rot,z_rot] = rot (x, y, z, theta, phi, eta)
% syms phi theta eta x y z;
% A = ...
% [ 1    0        0 ;...
% 0 cos(phi) -sin(phi);...
% 0 sin(phi) cos(phi)]*...
% [  cos(theta)   -sin(theta)   0;...
% sin(theta)   cos(theta)   0;...
% 0          0        1]*...
% [ cos(eta)   0   sin(eta);...
%  0        1        0     ;...
% -sin(eta)   0    cos(eta)]*[x ;z ;y ] 

x_rot = x*cos(eta)*cos(theta) - z*sin(theta) + y*cos(theta)*sin(eta);
y_rot = y*(cos(eta)*cos(phi) + sin(eta)*sin(phi)*sin(theta)) - x*(cos(phi)*sin(eta) - cos(eta)*sin(phi)*sin(theta)) + z*cos(theta)*sin(phi);
z_rot = x*(sin(eta)*sin(phi) + cos(eta)*cos(phi)*sin(theta)) - y*(cos(eta)*sin(phi) - cos(phi)*sin(eta)*sin(theta)) + z*cos(phi)*cos(theta);

end
